import type { Metadata } from 'next';
import './globals.css';
import { Provider } from '@/components/ui/provider';
import { Header } from '@/components/ui/header';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: Readonly<{
	children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
