name: Validate Develop

on:
  # developブランチのプルリクエストの作成がトリガー
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build
        run: node -v && yarn build
