name: Validate Develop

on:
  # developブランチのプルリクエストの作成がトリガー
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 22.12.0
        uses: actions/setup-node@v3
        with:
          node-version: "22.12.0"

      - name: Clean install
        run: |
          node -v
          rm -rf node_modules .prisma
          yarn install --frozen-lockfile

      - name: Generate Prisma Client
        run: yarn prisma generate

      - name: Build
        run: yarn build
