name: Validate Develop

on:
  # developブランチのプルリクエストの作成がトリガー
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clean install
        run: |
          node -v
          rm -rf node_modules .prisma
          yarn install --frozen-lockfile

      - name: Generate Prisma Client
        run: yarn prisma generate
        env:
          PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: "1"
          PRISMA_CLI_QUERY_ENGINE_TYPE: "binary"

      - name: Build
        run: yarn build
